FROM base:latest

EXPOSE 8245 

ENV $NOIP_HOME /noip

RUN wget http://www.no-ip.com/client/linux/noip-duc-linux.tar.gz
RUN tar xzf noip-duc-linux.tar.gz

ADD no-ip-2.1.9 /no-ip

WORKDIR /no-ip
RUN make
RUN make install

CMD ["/bin/bash", "-c", "/config/no-ip/no-ip.sh"]
